# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "Accenture"
email: "oscar.renalias@accenture.com"
description: "Open source is a driving force behind enterprise IT innovation, operational effectiveness and business value creation."
footer_line: "Opinions expressed on this blog reflect the writer's views and not the position of Accenture."
baseurl: "accenture.github.redesign" # this is for developing purposes only needs to be changed.
url: "https://accenture.github.io/" # the base hostname & protocol for your site
twitter_username: "AccentureTech"
github_username:  "accenture"
facebook_username:  "accenture"

# blog
permalink: /blog/:year/:month/:day/:title.html
gems: [jekyll-paginate]
paginate: 5
paginate_path: "/blog/page:num/"
blog_title: "Blog"
blog_intro: "Welcome to the Accenture blog series on GitHub. We will feature the opinions and perspectives from the very people that are creating open source software solutions and contributing Accenture technology to the open source community to drive innovation. We would like to use this forum to communicate and collaborate with our readers to help them think differently about technology."


# Build settings
markdown: kramdown

timezone: Europe/Helsinki
